# Generated by Django 5.0.3 on 2024-03-15 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineofferrequest',
            name='onlineoffer',
        ),
        migrations.RemoveField(
            model_name='onlineofferrequest',
            name='student',
        ),
        migrations.DeleteModel(
            name='OnlineOffer',
        ),
        migrations.DeleteModel(
            name='OnlineOfferRequest',
        ),
    ]
