# Generated by Django 5.0.3 on 2024-03-14 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='VIP Name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('language', models.CharField(choices=[('Frensh', 'Frensh'), ('English', 'English')], max_length=10, verbose_name='Language')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.course')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.teacher')),
            ],
            options={
                'verbose_name': 'VIP Course',
                'verbose_name_plural': 'VIP Courses',
                'db_table': 'VIP_Course',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='VIPClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Class Name')),
                ('zoom_link', models.CharField(max_length=255, verbose_name='Zoom Link')),
                ('classroom_link', models.CharField(max_length=255, verbose_name='Classroom Link')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.teacher')),
                ('vip_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VIP.vipcourse')),
            ],
            options={
                'verbose_name': 'VIP Class',
                'verbose_name_plural': 'VIP Classes',
                'db_table': 'VIP_Class',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='VIPMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('voice', models.FileField(blank=True, null=True, upload_to='voice/%y/%m/%d', verbose_name='Voice')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/%y/%m/%d', verbose_name='Image')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vipclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VIP.vipclass')),
            ],
            options={
                'verbose_name': 'VIP Message',
                'verbose_name_plural': 'VIP Messages',
                'db_table': 'VIP_Message',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='VIPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.student')),
                ('vip_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VIP.vipcourse')),
            ],
            options={
                'verbose_name': 'VIP Request',
                'verbose_name_plural': ' VIP Requests',
                'db_table': 'VIP_Request',
                'ordering': ['-created'],
            },
        ),
    ]
