# Generated by Django 5.0.3 on 2024-03-14 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Class Name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('language', models.CharField(choices=[('Frensh', 'Frensh'), ('English', 'English')], max_length=10, verbose_name='Language')),
                ('classroom_link', models.CharField(max_length=255, verbose_name='Classroom Link')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.course')),
                ('students', models.ManyToManyField(blank=True, to='Main.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.teacher')),
            ],
            options={
                'verbose_name': 'Offline Class',
                'verbose_name_plural': 'Offline Classes',
                'db_table': 'Offline_Class',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OfflineMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('voice', models.FileField(blank=True, null=True, upload_to='voice/%y/%m/%d', verbose_name='Voice')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/%y/%m/%d', verbose_name='Image')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('offlineclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Offline.offlineclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offline Message',
                'verbose_name_plural': 'Offline Messages',
                'db_table': 'Offline_Message',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='OfflineOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('offlineclasses', models.ManyToManyField(blank=True, to='Offline.offlineclass')),
            ],
            options={
                'verbose_name': 'Offline Offer',
                'verbose_name_plural': 'Offline Offers',
                'db_table': 'Offline_Offer',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OfflineOfferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('offlineoffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Offline.offlineoffer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.student')),
            ],
            options={
                'verbose_name': 'Offline Offer Request',
                'verbose_name_plural': ' Offline Offer Requests',
                'db_table': 'Offline_Offer_Request',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OfflineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('offlineclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Offline.offlineclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.student')),
            ],
            options={
                'verbose_name': 'Offline Request',
                'verbose_name_plural': ' Offline Requests',
                'db_table': 'Offline_Request',
                'ordering': ['-created'],
            },
        ),
    ]
