# Generated by Django 5.0.3 on 2024-03-15 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Offline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlineofferrequest',
            name='offlineoffer',
        ),
        migrations.RemoveField(
            model_name='offlineofferrequest',
            name='student',
        ),
        migrations.DeleteModel(
            name='OfflineOffer',
        ),
        migrations.DeleteModel(
            name='OfflineOfferRequest',
        ),
    ]
