"""
Django settings for AcedmiTechLearn project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2z9^rnq%ebpqiq^tfa3@e#f3%a&@h3fzl8d&+3_u^njv@)2olg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Main',
    'Offline',
    'Online',
    'VIP',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AcedmiTechLearn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AcedmiTechLearn.wsgi.application'
ASGI_APPLICATION = 'AcedmiTechLearn.asgi.application'

# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer'
#     },
# }

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': '',
#         'USER': '',
#         'PASSWORD': '',
#         'HOST': '',
#         'PORT': '',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Beirut'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = True

# JAZZMIN_SETTINGS = {
#     "site_title": "GoTop Acedemy Admin",
#     "site_header": "GoTop Acedemy",
#     "site_brand": "GoTop Acedemy",
#     "welcome_sign": "Welcome to the Admin Panel",
#     "copyright": "Wizo Team",
#     "order_with_respect_to": ["App1.Student", "App1.Teacher", "App1.Course", "App1.OnlineClass", "App1.OnlineRequest",
#                               "App1.OnlineOffer", "App1.OnlineOfferRequest", "App1.OnlineMessage", "App1.OfflineClass",
#                               "App1.OfflineRequest", "App1.OfflineOffer", "App1.OfflineOfferRequest",
#                               "App1.OfflineMessage", "App1.VIPCourse", "App1.VIPClass", "App1.VIPRequest",
#                               "App1.VIPMessage", "App1.Inbox"],
#     "icons": {
#         "auth": "fas fa-users-cog",
#         "auth.user": "fas fa-user",
#         "auth.Group": "fas fa-users",
#
#         "App1.Student": "fa fa-user",
#         "App1.Teacher": "fa fa-graduation-cap",
#         "App1.Course": "fa fa-book",
#
#         "App1.OnlineClass": "fa fa-book",
#         "App1.OnlineRequest": "fa fa-inbox",
#         "App1.OnlineOffer": "fa fa-box",
#         "App1.OnlineOfferRequest": "fa fa-inbox",
#         "App1.OnlineMessage": "fa fa-comments",
#
#         "App1.OfflineClass": "fa fa-book",
#         "App1.OfflineRequest": "fa fa-inbox",
#         "App1.OfflineOffer": "fa fa-box",
#         "App1.OfflineOfferRequest": "fa fa-inbox",
#         "App1.OfflineMessage": "fa fa-comments",
#
#         "App1.VIPCourse": "fa fa-book",
#         "App1.VIPClass": "fa fa-book",
#         "App1.VIPRequest": "fa fa-inbox",
#         "App1.VIPMessage": "fa fa-comments",
#
#         "App1.Inbox": "fa fa-inbox",
#     },
# }